#!/usr/bin/env php
<?php
require_once 'spark_support/spark_source.php';
require_once 'spark_support/spark_cli.php';

// define a source
$source = new SparkSource('sparks.oconf.org');

// take commands
$cli = new SparkCLI($source);
if ($argc > 1) $cli->execute($argv[1], array_slice($argv, 2));
